[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
name = "cayleypy"
version = "0.1.0"
description = "Library for studying Cayley graphs and Schreier coset graphs"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "CayleyPy Foundation" }]

# https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering :: Mathematics",
]

# https://peps.python.org/pep-0508/
dependencies = [
    "h5py",
    "kagglehub",
    "numba",
    "numpy",
    "scipy",
    "torch>=2.6.0",
]

# Development dependencies
# pip install .[torch,lint,test,dev,docs]
[project.optional-dependencies]
lint = [
    "black==25.1.0",
    "pyright==1.1.411",
]
test = [
    "pytest",
    "pytest-benchmark",
]
dev = [
    "coverage",
    "networkx",
    "setuptools",
]
docs = [
    # Libraries needed to build documentation.
    "sphinx>=9.1.0",
    "sphinx_rtd_theme",
]

[project.urls]
"Homepage" = "https://github.com/cayleypy/cayleypy"
"Documentation" = "https://cayleypy.github.io/cayleypy-docs/api.html"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"cayleypy" = ["data/*.csv", "puzzles/gap_files/**"]

[tool.black]
line-length = 120
