[[tool.mypy.overrides]]
module = ["networkx.*"]
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = ["tensorflow.*"]
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = ["numba.*"]
ignore_missing_imports = true

[tool.black]
line-length = 120
